import Head from "next/head";
import { AiOutlineGoogle } from "react-icons/ai";
import { signInWithPopup, GoogleAuthProvider } from "firebase/auth";
import { auth } from "../../utils/firebase";
import { useRouter } from "next/router";
import { useAuthState } from 'react-firebase-hooks/auth';
import { useEffect } from "react";
import { FullScreenNavbar } from "../../components/FullScreenNavbar";
import Link from "next/link";

const Login = () => {
  const route = useRouter();
  //Sign in with google
  const [user, loading] = useAuthState(auth);
  const googleProvider = new GoogleAuthProvider();
  const GoogleLogin = async () => {
    try {
      const result = await signInWithPopup(auth, googleProvider);
      route.push("/");
    } catch (error) {
      console.log(error);
    }
  };
  useEffect(() => {
    if (user) {
      route.push("/Post");
    } else {
      console.log("login");
    }
  }, [user]);

  return (
    <div>
        <Head>
          <title>Confessay</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon.png" />
          <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
          <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
          <link rel="manifest" href="/site.webmanifest" />
          <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
          <meta name="msapplication-TileColor" content="#da532c" />
          <meta name="theme-color" content="#ffffff" />
        </Head> 
      <nav className="py-10 mb-12 flex justify-between items-center px-5">
          <ul className="flex">
          <li>
          <Link href="/" legacyBehavior>
              <button>
              <h1 className="text-2xl md:text-7xl text-cyan-700 font-cormorant font-bold italic tracking-wider">Confessay</h1>
              </button>
          </Link>
          </li>
          </ul>
          <FullScreenNavbar />
      </nav>

      <div className="shadow-xl mt-32 p-10 text-gray-700 rounded-lg">
        <h2 className="text-2xl font-semibold font-medium">Join Today</h2>
        <div className="py-4">
          <h3 className="py-4 font-medium">Sign in with one of the providers</h3>
          <button
            onClick={GoogleLogin}
            className="text-white bg-gray-700 w-full font-medium rounded-lg flex align-middle p-4 gap-2"
          >
            <AiOutlineGoogle className="text-2xl font-medium" />
            Sign in with Google
          </button>
        </div>
      </div>
    </div>
  );
}
 
export default Login;
